# fly.toml app configuration file generated for lnfly on 2025-04-19T14:52:59+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lnfly'
primary_region = 'fra'
swap_size_mb = 2048

[build]

[env]
  BASE_URL = 'https://lnfly.fly.dev'
  DATABASE_URL = 'file:/data/lnfly.db'

[[mounts]]
  source = 'lnfly_data'
  destination = '/data'
  initial_size = '1'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '1m0s'
    timeout = '5s'
    grace_period = '45s'
    method = 'GET'
    path = '/ping'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
